AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Elastic Beanstalk Environment with S3 and RDS

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'your-s3-bucket-name-${AWS::StackName}-${AWS::Region}'

  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: your-db-instance
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: OneAnotherAdminUser
      MasterUserPassword: OneTestOfThose123!!X0934Dz#
      DBName: OneAnotherDb

  ElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: OneAnother

  ElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: Development
      SolutionStackName: '64bit Amazon Linux 2023 v3.3.0 running .NET 9'
      OptionSettings:
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'S3_BUCKET'
          Value: !Ref S3Bucket
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'DB_CONNECTION_STRING'
          Value: !Sub 'Server=${RDSInstance.Endpoint.Address};Database=OneAnotherDb;User Id=OneAnotherAdminUser;Password=OneTestOfThose123!!X0934Dz#;'

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref S3Bucket

  RDSInstanceEndpoint:
    Description: 'Endpoint of the RDS instance'
    Value: !GetAtt RDSInstance.Endpoint.Address

  ElasticBeanstalkEnvironmentURL:
    Description: 'URL of the Elastic Beanstalk Environment'
    Value: !GetAtt ElasticBeanstalkEnvironment.EndpointURL