AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an AWS Elastic Beanstalk environment for .NET 9 API deployment

Parameters:
  ApplicationName:
    Type: String
    Default: DotnetApiApp
    Description: Name of the Elastic Beanstalk application
  EnvironmentName:
    Type: String
    Default: DotnetApiEnv
    Description: Name of the Elastic Beanstalk environment
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dotnet-api-deployment-${AWS::AccountId}"

  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName

  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: "64bit Amazon Linux 2 v5.8.1 running .NET Core"
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: "SingleInstance"
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DOTNET_ENVIRONMENT
          Value: "Production"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: !Sub 'arn:aws:s3:::dotnet-api-deployment-${AWS::AccountId}/*'
        - PolicyName: ElasticBeanstalkAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'elasticbeanstalk:*'
                  - 'ec2:*'
                  - 's3:*'
                Resource: '*'

Outputs:
  EnvironmentURL:
    Description: URL of the Elastic Beanstalk environment
    Value: !Sub "http://${ElasticBeanstalkEnvironment.EndpointURL}"
