AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Elastic Beanstalk Environment with S3 and RDS

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'your-s3-bucket-name-${AWS::StackName}-${AWS::Region}'

  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: your-db-instance
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro
      Engine: sqlserver-ex
      EngineVersion: '15.00.4043.16.v1'
      MasterUsername: OneAnotherAdminUser
      MasterUserPassword: OneTestOfThose123!!X0934Dz#
      DBName: OneAnotherDb
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup

  RDSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access to RDS instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

  ElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: OneAnother

  ElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: Development
      SolutionStackName: '64bit Amazon Linux 2023 v3.3.0 running .NET 9'
      OptionSettings:
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'S3_BUCKET'
          Value: !Ref S3Bucket
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'DB_CONNECTION_STRING'
          Value: !Sub 'Server=${RDSInstance.Endpoint.Address};Database=OneAnotherDb;User Id=OneAnotherAdminUser;Password=OneTestOfThose123!!X0934Dz#;'
      Tier:
        Name: WebServer
        Type: Standard
        Version: '1.0'
      EnvironmentLinks:
        - LinkName: RDSLink
          EnvironmentName: !Ref RDSInstance

  ElasticBeanstalkInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref ElasticBeanstalkRole

  ElasticBeanstalkRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ElasticBeanstalkPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - rds:*
                  - ec2:*
                Resource: '*'

  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpc'

  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-southeast-2a

  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-southeast-2a

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref S3Bucket

  RDSInstanceEndpoint:
    Description: 'Endpoint of the RDS instance'
    Value: !GetAtt RDSInstance.Endpoint.Address

  ElasticBeanstalkEnvironmentURL:
    Description: 'URL of the Elastic Beanstalk Environment'
    Value: !GetAtt ElasticBeanstalkEnvironment.EndpointURL
