AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to deploy a .NET application to Elastic Beanstalk with an MSSQL database and S3 bucket.

Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  # Subnet
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs !Ref "AWS::Region"]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-subnet

  # Internet Gateway
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-igw

  # Attach Internet Gateway to VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  # Route Table
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-rt

  # Route
  MyRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  # Subnet Route Table Association
  MySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet
      RouteTableId: !Ref MyRouteTable

  # S3 Bucket
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  # Elastic Beanstalk Application
  MyApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub ${AWS::StackName}-app
      Description: AWS Elastic Beanstalk Application for .NET application

  # Elastic Beanstalk Environment
  MyEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref MyApplication
      EnvironmentName: !Sub ${AWS::StackName}-env
      SolutionStackName: "64bit Windows Server 2019 v2.7.2 running IIS 10.0"
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ASPNETCORE_ENVIRONMENT
          Value: "Production"
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: CONNECTIONSTRINGS__DefaultConnection
          Value: !Sub "Server=${MyDBInstance.Endpoint.Address};Database=${DBName};User Id=${DBUser};Password=${DBPassword};"

  # Security Group for RDS
  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to RDS instance
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 0.0.0.0/0

  # RDS MSSQL Database
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${AWS::StackName}-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: sqlserver-se
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref MyDBSecurityGroup
      DBName: !Ref DBName

  # Elastic Beanstalk Application Version
  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref MyApplication
      SourceBundle:
        S3Bucket: !Ref MyS3Bucket
        S3Key: myapp.zip

Parameters:
  DBUser:
    Type: String
    Description: The database admin account username
    NoEcho: true
  DBPassword:
    Type: String
    Description: The database admin account password
    NoEcho: true
  DBName:
    Type: String
    Description: The name of the database

Outputs:
  ApplicationURL:
    Description: URL of the Elastic Beanstalk application
    Value: !GetAtt MyEnvironment.EndpointURL
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
  VPCId:
    Description: ID of the VPC
    Value: !Ref MyVPC