name: "Authorize AWS Session"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS SSO
        run: |
          aws configure set sso_start_url ${{ secrets.AWS_SSO_START_URL }}
          aws configure set sso_region ${{ secrets.AWS_REGION }}
          aws configure set sso_account_id ${{ secrets.AWS_ACCOUNT_ID }}
          aws configure set sso_role_name ${{ secrets.AWS_ROLE_NAME }}

      - name: Login to AWS via SSO
        run: aws sso login

      - name: Retrieve AWS Credentials
        run: |
          aws sso get-role-credentials --account-id ${{ secrets.AWS_ACCOUNT_ID }} --role-name ${{ secrets.AWS_ROLE_NAME }} > creds.json
          export AWS_ACCESS_KEY_ID=$(jq -r '.roleCredentials.accessKeyId' creds.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r '.roleCredentials.secretAccessKey' creds.json)
          export AWS_SESSION_TOKEN=$(jq -r '.roleCredentials.sessionToken' creds.json)

      - name: Store Credentials in GitHub Secrets
        run: |
          gh secret set AWS_ACCESS_KEY_ID --body "$AWS_ACCESS_KEY_ID"
          gh secret set AWS_SECRET_ACCESS_KEY --body "$AWS_SECRET_ACCESS_KEY"
          gh secret set AWS_SESSION_TOKEN --body "$AWS_SESSION_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
