name: Deploy Web API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore OneAnother/src/Web/Web.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore OneAnother/src/Web/Web.csproj

    - name: Publish
      run: dotnet publish -c Release -o ./publish OneAnother/src/Web/Web.csproj

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Deploy CloudFormation stack
      id: deploy-stack
      run: aws cloudformation deploy --template-file OneAnother/.aws/cloudformation.yaml --stack-name oneanother-dev --capabilities CAPABILITY_NAMED_IAM

    - name: Get S3 bucket name
      id: get-s3-bucket
      run: echo "S3_BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name oneanother-dev --query 'Stacks[0].Outputs[?OutputKey==`S3BucketName`].OutputValue' --output text)" >> $GITHUB_ENV

    - name: Upload to S3
      run: aws s3 cp ./publish s3://$S3_BUCKET_NAME/ --recursive