name: "Deploy to AWS"

on:
  push:
    branches:
      - main

jobs:
  authorize:
    uses: ./.github/workflows/authorize.yml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: authorize
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        run: |
          echo "Configuring AWS credentials..."
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yaml \
            --stack-name my-cloud-stack \
            --region ${{ secrets.AWS_REGION }} \
            --capabilities CAPABILITY_NAMED_IAM
