name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore OneAnother/src/Web/Web.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore OneAnother/src/Web/Web.csproj

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --no-build OneAnother/src/Web/Web.csproj

      - name: Zip published files
        run: zip -r myapp.zip ./publish

      - name: Deploy CloudFormation stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
        run: |
          aws cloudformation deploy \
            --template-file OneAnother/.aws/cloudformation.yaml \
            --stack-name my-cloudformation-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              VPC=$VPC_ID \
              DBUser=$DB_USER \
              DBPassword=$DB_PASSWORD \
              DBName=$DB_NAME

      - name: Retrieve S3 bucket name
        id: get_s3_bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
        run: |
          S3_BUCKET=$(aws cloudformation describe-stacks --stack-name my-cloudformation-stack --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" --output text)
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV

      - name: Upload to S3
        run: aws s3 cp myapp.zip s3://$S3_BUCKET/myapp.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2