name: Deploy Web API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore OneAnother/src/Web/Web.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore OneAnother/src/Web/Web.csproj

    - name: Publish
      run: dotnet publish -c Release -o ./publish OneAnother/src/Web/Web.csproj

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Deploy CloudFormation stack
      id: deploy-stack
      run: aws cloudformation deploy --template-file OneAnother/.aws/cloudformation.yaml --stack-name oneanother-dev --capabilities CAPABILITY_NAMED_IAM

    - name: Upload to Elastic Beanstalk S3 bucket
      run: |
        zip -r deploy.zip ./publish
        aws s3 cp deploy.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-123456789012/deploy.zip
