name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
            
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials Action for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: ap-southeast-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Determine stack name
      id: stack-name
      run: echo "STACK_NAME=one-another-${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Validate CloudFormation template
      run: |
        aws cloudformation validate-template --template-body file://OneAnother/.aws/cloudformation.yaml

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file OneAnother/.aws/cloudformation.yaml \
          --capabilities CAPABILITY_NAMED_IAM